name: Deploy to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: firstwebapp    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './firstwebapp'  # set this to your project name
  DOTNET_VERSION: '8.0.x'             # set this to the .NET Core version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: List directory contents
      run: ls -R

    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{env.DOTNET_ROOT}}/myapp